[package]
name = "tetris"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
crossterm = "0.29.0"
device_query = "3.0.1"
ndarray = "0.16.1"
rand = "0.9.1"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
